<?php 	$url = $this->baseUrl('/images/escape/');
		$this->headScript()->captureStart()?>
	$(function(){
		$('#building_code').change(function(event){
			$.ajax({
					type: 'POST',
					url: '<?= $this->url(array('controller' => 'staff', 'action' => 'floornumber'), 'default'); ?>',
					data: "code="+$('#building_code').val(),
					datatype: 'json',
					success: setFloor
			});
		});			
	});


	function setFloor(data){
		$('#floor_number').find('option').remove();
		$('#zone_number').find('option').remove();
		$('#escape_map').find('option').remove();
		$('#floor_number').append('<option>-- Select --</option>'); 
		var floor = parseInt(data['floor_number']); 
		$.each(data,function(key, val){ 
			$('#floor_number').append('<option value="' + val['code'] + '">' + val['number'] + '</option>');
        });
	};
	
	
	
	$(function(){
		$('#floor_number').change(function(event){
			$.ajax({
				type: 'POST',
				url: '<?= $this->url(array('controller' => 'staff', 'action' => 'zonenumber'), 'default'); ?>',
				data: "code="+$('#floor_number').val(),
				datatype: 'json',
				success: setZone
			});
		});
	});

	function setZone(data){
		$('#zone_number').find('option').remove();
		$('#escape_map').find('option').remove();
		$('#zone_number').append('<option>-- Select --</option>');
		var zone = parseInt(data['zone_number']);
		$.each(data, function(key, val){
	    	$('#zone_number').append('<option value="' + val['code'] + '">' + val['number'] + '</option>');
	    });
	};
	  
	  
	  
	$(function(){
		$('#zone_number').change(function(event){
			$.ajax({
				type: 'POST',
				url: '<?= $this->url(array('controller' => 'staff', 'action' => 'escapemap'), 'default'); ?>',
				data: "code="+$('#zone_number').val(),
				datatype: 'json',
				success: setMap
			});
		});
	});

	function setMap(data){
		$('#escape_map').find('option').remove();
		$('#escape_map').append('<option>-- Select --</option>');
		$.each(data, function(key, val){
	    	$('#escape_map').append('<option value="' + val['image'] + '">' + val['image'] + '</option>');
	    });
	};
	
	
	$(function(){
		$('#escape_map').change(function(event){
					$('#image_escape').find('img').remove();
					var image = $('#escape_map :selected').text();
				    $('#image_escape').append('<img src="<?= $url?>' + image + '" width="400"/>'); 
		});
	});
<?php $this->headScript()->captureEnd()?>
<div class="row">
	<div class="col-sm-12">
		<hgroup id="titolo">
			<h2 class="text-center">Associazione Zona Fuga</h2>
			<h4 class="text-center">Utilizza questa form per associare una via di fuga con una zona</h4>
		</hgroup>
		
	</div>
	<div class="col-sm-4">
		<?= $this->associateForm; ?>
	</div>
	<div id="image_escape" class="col-sm-8">
		
	</div>
</div>