<div class="row">
	<div class="col-lg-12">
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<img src="<?= $this->baseUrl("css/images/user.jpg");?>" class="img-user img-circle img-thumbnail img-responsive">
				</div>
				<div class="col-sm-3 utente">
					<p class="h3"><?= $this->authInfo('name');?> <?= $this->authInfo('surname');?></p>
					<p class="h5">Username : <?= $this->authInfo('user');?></p>
				</div>
				<div class="col-sm-2 dati-utente">
					<p class="h3">Ruolo</p>
					<p class="h5"><?= strtoupper($this->authInfo('role'));?></p>
				</div>
				<div class="col-sm-2 mail">
					<p class="h3">Email</p>
					<p class="h5"><?= $this->authInfo('mail');?></p>
				</div>
				<div class="col-sm-2 password">
					<a href="<?= $this->url(array(
					'controller' => 'staff',
					'action' => 'modifyprofile',
					'user' => $this->authInfo('user')),
					'default', true); ?>" class="h4"><small>Modifica profilo</small></a>
				</div>
			</div>
		</div>
	</div>
</div>