<div class="row">
	<div class="col-sm-12">
		<h1 class="text-center">L'azienda</h1>
		<hr />
		<article>
			<p>
				<img src="<?= $this->baseUrl('css/images/why.jpg'); ?>" alt="azienda" title="azienda"
					class="didascalia-azienda img-thumbnail img-responsive" />Lorem
				ipsum dolor sit amet, consectetur adipiscing elit. Sed in egestas
				arcu. Proin quis nisl condimentum, dignissim nibh non, fermentum
				urna. Class aptent taciti sociosqu ad litora torquent per conubia
				nostra, per inceptos himenaeos. Sed dignissim ornare rhoncus.
				Maecenas cursus nunc vel turpis rhoncus, maximus eleifend lorem
				auctor. Mauris quis euismod ipsum, quis sollicitudin libero. Sed
				nulla velit, malesuada ac dolor eu, convallis pharetra diam.
				Pellentesque ut interdum sem. Donec mattis nunc sit amet pulvinar
				porta. Curabitur sagittis augue id pharetra varius. Praesent id sem
				mi. Duis auctor est erat, et varius elit venenatis in. Fusce sed
				gravida nunc, in auctor ex. Phasellus maximus faucibus metus nec
				ultrices. Donec efficitur sed leo a fermentum. Mauris porttitor
				fermentum odio, id luctus augue euismod sed. Curabitur ut lorem eget
				leo iaculis aliquet. Aliquam ac leo interdum, aliquam turpis eget,
				rutrum diam. Etiam malesuada augue at facilisis faucibus. Nulla
				facilisi. Pellentesque tempor urna arcu, a euismod nulla mollis nec.
				Proin tincidunt sed odio nec imperdiet. Fusce magna ipsum, mollis
				nec aliquam accumsan, fermentum id enim.
			</p>
			<p>Donec diam lectus, hendrerit eu lacinia vitae, semper sit amet
				augue. Nulla porta ex eget aliquam consequat. Maecenas blandit neque
				enim, ac mollis dui posuere vel. Nam est velit, accumsan in
				dignissim ut, consectetur nec dui. Sed fermentum accumsan elit ut
				tincidunt. Suspendisse cursus odio odio, nec ultrices sapien
				sagittis at. Fusce ultrices justo mi. Duis sit amet felis nunc.
				Suspendisse non nisi elit. Duis tempus tristique neque, ut fringilla
				ipsum faucibus et.</p>
			<p>Mauris orci sapien, pharetra non commodo eget, auctor eu odio.
				Mauris porta turpis ut bibendum mattis. Donec pretium turpis ut orci
				vestibulum congue. Praesent ex mi, tempor vitae sodales sed, feugiat
				ac nisl. Sed mollis mollis velit, a iaculis augue ornare eu. Etiam
				venenatis pulvinar mollis. Quisque quis mi arcu. Nulla dapibus
				semper ante non dignissim. Nam a pulvinar tellus. Nam laoreet a ante
				eu tristique. Donec vulputate maximus ornare. Vivamus egestas sapien
				nec nisi feugiat tincidunt. In vel turpis neque. In rutrum justo ut
				tempus posuere. Mauris sagittis malesuada vulputate. Donec fringilla
				nibh ut dui condimentum, nec aliquam sem dignissim. Morbi vel ex
				lacus. Aliquam feugiat id mauris et mattis. Phasellus porta sem ac
				justo aliquam, ac congue turpis porttitor.</p>
		</article>
	</div>
</div>
<div class="row">
	<div class="col-sm-12">
		<h2 class="text-center">Il Team</h2>
		<hr />
	</div>
	<div class="col-sm-3">
		<div class="thumbnail-team">
			<img src="<?= $this->baseUrl('css/images/elia.jpg'); ?>"
				class="img-responsive img-circle icon-team" />
		</div>
		<h4 class="text-center">Elia Pacioni</h4>
		<p class="text-center">
			<a href="#"> <img src="<?= $this->baseUrl('css/images/fb.png'); ?>" />
			</a> <a href="#"> <img src="<?= $this->baseUrl('css/images/tw.png'); ?>" /></a>
		</p>
	</div>
	<div class="col-sm-3">
		<div class="thumbnail-team">
			<img src="<?= $this->baseUrl('css/images/simone.jpg'); ?>"
				class="img-responsive img-circle icon-team" />
		</div>
		<h4 class="text-center">Simone Onori</h4>
		<p class="text-center">
			<a href="#"> <img src="<?= $this->baseUrl('css/images/fb.png'); ?>" />
			</a> <a href="#"> <img src="<?= $this->baseUrl('css/images/tw.png') ?>" /></a>
		</p>
	</div>
	<div class="col-sm-3">
		<div class="thumbnail-team">
			<img src="<?= $this->baseUrl('css/images/smero.jpg'); ?>"
				class="img-responsive img-circle icon-team" />
		</div>
		<h4 class="text-center">Riccardo Smerilli</h4>
		<p class="text-center">
			<a href="#"> <img src="<?= $this->baseUrl('css/images/fb.png'); ?>" />
			</a> <a href="#"> <img src="<?= $this->baseUrl('css/images/tw.png'); ?>" /></a>
		</p>
	</div>
	<div class="col-sm-3">
		<div class="thumbnail-team">
			<img src="<?= $this->baseUrl('css/images/matteo.jpg'); ?>"
				class="img-responsive img-circle icon-team" />
		</div>
		<h4 class="text-center">Matteo Sanguigni</h4>
		<p class="text-center">
			<a href="#"> <img src="<?= $this->baseUrl('css/images/fb.png'); ?>" />
			</a> <a href="#"> <img src="<?= $this->baseUrl('css/images/tw.png'); ?>" /></a>
		</p>
	</div>
</div>