<div class="row">
	<div class="col-sm-6">
		<h3>Modulo di Contatto</h3>
		<hr/>
 		<?=$this->contactForm; ?>
	</div>
	<div class="col-sm-6">
		<section id="recapiti" class="text-right">
			<h3>Recapiti</h3>
			<hr/>
			<address>
				<strong>SOPS ESCAPE S.p.A</strong><br /> Via dei Cavalieri, 600<br />
				Ancona, 00100, Italy<br /> Telefono/fax: 123 456-7890
			</address>
			<address>
				E-mail<br /> <a href="mailto:info@fakeboot.com"></a> <a
					href="mailto:sops@sops.com">sops@sops.com</a>
			</address>
		</section>
	</div>
</div>