<div class="row">
	<div class="col-sm-8 col-sm-offset-2">
		<h2 class="text-center">F.A.Q.</h2>
		<hr />
		<div class="panel">
			<div class="panel-group" id="accordion">
				<?php $i = 0;?>
				<?php foreach($this->faq as $faq) : ?>
				<div class="panel panel-default">
					<div class="panel-heading">
						<h4 class="panel-title">
							<a class="accordion-toggle collapsed" data-toggle="collapse"
								data-parent="#accordion" href="#faq<?= $i; ?>"> <?= $faq->question; ?> </a>
						</h4>
					</div>
					<div id="faq<?= $i++; ?>" class="panel-collapse collapse">
						<div class="panel-body"> <?= $faq->answer; ?></div>
					</div>
				</div>
				<?php endforeach; ?>
			</div>
		</div>
	</div>
</div>