<div class="row">
	<div class="col-sm-12">
		<h2 class="text-center">Perche registrarsi?</h2>
		<br />
	</div>
	<div class="col-sm-3">
		<img src="<?= $this->baseUrl('css/images/why.jpg'); ?>" class="img-responsive img-thumbnail" alt=""
			title="" />
	</div>
	<div class="col-sm-9">
		<article class="text-justify">
			<p>Lorem Ipsum è un testo segnaposto utilizzato nel settore della
				tipografia e della stampa. Lorem Ipsum è considerato il testo
				segnaposto standard sin dal sedicesimo secolo, quando un anonimo
				tipografo prese una cassetta di caratteri e li assemblò per
				preparare un testo campione.</p>

			<p>È sopravvissuto non solo a più di cinque secoli, ma anche al
				passaggio alla videoimpaginazione, pervenendoci sostanzialmente
				inalterato.</p>
			<p>Fu reso popolare, negli anni ’60, con la diffusione dei fogli di
				caratteri trasferibili “Letraset”, che contenevano passaggi del
				Lorem Ipsum, e più recentemente da software di impaginazione come
				Aldus PageMaker, che includeva versioni del Lorem Ipsum.</p>
		</article>
	</div>
	<div class="col-sm-12 text-center" style="padding: 30px;">
		<a class="btn btn-lg btn-success" href="#">Registrati</a>

	</div>
</div>