<div class="row service">
	<div class="col-sm-4">
		<h4 class="text-center">Corsi di primo soccorso</h4>
		<br />
		<br />
		<p class="text-justify">Per le aziende privata la SOPS ESCAPE
			organizza corsi di primo soccorso. I corsi sono gestiti da personale
			qualificato, nelle 20 ore di corso è prevista l’acquisizione delle
			basilari conoscenze per affrontare al meglio qualsiasi tipo di
			emergenza. Alla fine del corso verrà rilasciato un certificato
			approvato e riconosciuto dagli organi amministrativi competenti.</p>
	</div>
	<div class="col-sm-4 serv">
		<h4 class="text-center">Organizzazione piani di sicurezza e consulenza
			in tempo reale</h4>
		<br />
		<p class="text-justify">Sops Escape è un’azienda specializzata
			nell’organizzazione e nella gestione di piani di evacuazione di
			edifici pubblici e privati. È l’unica azienda del settore che
			fornisce una consulenza in tempo reale mediante piattaforma web agli
			utenti in caso di pericoli di vario genere. Un team specializzato si
			occuperà di fornire una mappa dov’è indicata la via di fuga più
			vicina in base alla vostra posizione, assicurandovi di seguire il
			percorso più sicuro verso l’uscita.</p>
	</div>
	<div class="col-sm-4">
		<h4 class="text-center">Perizie e installazioni</h4>
		<br />
		<br />
		<p class="text-justify">Il nostro personale sarà a disposizione per
			effettuare perizie su impianti di sicurezza già esistenti e per
			sopralluoghi finalizzati alla messa in sicurezza degli immobili.
			Lasciatevi consigliare da esperti del settore la soluzione migliore
			al vostro caso.</p>
	</div>

</div>