<?php $log = Zend_Auth::getInstance()->hasIdentity(); ?>

<a class="navbar-brand logo" href="<?php if (!$log):?>
	<?= $this->url(array('controller' => 'public','action' => 'index',),'default', true); ?>
	<? else :?>
	<?= $this->url(array('controller' => 'user','action' => 'index',),'default', true); ?>
	<? endif; ?>
	">SOPS ESCAPE</a>
</div>

<ul class="nav navbar-nav">
	<li><a href="
	<?php if (!$log): ?>
	<?=$this->url ( array ('controller' => 'public','action' => 'index' ), 'default', true );?>
	<?php else :?>
	<?=$this->url ( array ('controller' => 'user','action' => 'index' ), 'default', true );?>
	<?php endif; ?>
	">Home</a></li>
	<li><a
		href="<?=$this->url ( array ('controller' => 'public','action' => 'viewstatic','staticPage' => 'chisiamo' ), 'default', true );?>">Chi Siamo</a></li>
	<li><a
		href="<?=$this->url ( array ('controller' => 'public','action' => 'viewstatic','staticPage' => 'servizi' ), 'default', true );?>">Servizi</a></li>
	<li><a
		href="<?=$this->url ( array ('controller' => 'public','action' => 'contact' ), 'default', true );?>">Contatti</a></li>
</ul>
<div class="login-top">
	<ul class="nav navbar-nav navbar-right">
	<?php $role = $this->authInfo('role'); ?>
	<?php if ($role == 'admin'): ?>
		<li><a href="<?=$this->url ( array ('controller' => 'admin','action' => 'index' ), 'default', true );?>">Amministrazione</a></li>
	<?php endif; ?>
	<?php if (!$log): ?>
		<li><a href="<?=$this->url ( array ('controller' => 'public','action' => 'login' ), 'default', true );?>">Login</a></li>
		<li><a href="<?=$this->url ( array ('controller' => 'public','action' => 'registration' ), 'default', true );?>">Registrati</a></li>
	<?php else :?> 
		<li><a href="<?=$this->url ( array ('controller' => 'user','action' => 'logout' ), 'default', true );?>">Logout</a></li>
		<li><a href="<?=$this->url ( array ('controller' => 'user','action' => 'viewprofile' ), 'default', true );?>">Profilo</a></li>
	<?php endif; ?>
	</ul>
</div>