<ul class="nav navbar-nav">
	<li><a href="<?= $this->url(array(
			'controller' => 'public',
			'action' => 'index',
			), 
			'default', true); ?>">Home</a></li>
	<li><a href="<?= $this->url(array(
			'controller' => 'public',
			'action' => 'viewstatic',
			'staticPage' => 'chisiamo'
			), 
			'default', true); ?>">Chi Siamo</a></li>
	<li><a href="<?= $this->url(array(
			'controller' => 'public',
			'action' => 'viewstatic',
			'staticPage' => 'servizi'
			), 
			'default', true); ?>">Servizi</a></li>
	<li><a href="<?= $this->url(array(
			'controller' => 'public',
			'action' => 'contact'),
			'default', true);?>">Contatti</a></li>
</ul>
<div class="login-top">
	<ul class="nav navbar-nav navbar-right">
		<li><a href="<?= $this->url(array(
				'controller' => 'public',
				'action' => 'login'
				), 
				'default', true); ?>">Login</a></li>
		<li><a href="<?= $this->url(array(
				'controller' => 'public',
				'action' => 'registration'
				),
				'default', true); ?>">Registrati</a></li>
	</ul>
</div>