<ul class="nav navbar-nav">
	<li><a href="<?= $this->url(array(
			'controller' => 'user',
			'action' => 'index',
			), 
			'default', true); ?>">Home</a></li>
	<?php /* <li><a href="<?= $this->url(array(
			'controller' => 'public',
			'action' => 'viewstatic',
			'staticPage' => 'chisiamo'
			), 
			'default', true); ?>">Chi Siamo</a></li>
	<li><a href="<?= $this->url(array(
			'controller' => 'public',
			'action' => 'viewstatic',
			'staticPage' => 'servizi'
			), 
			'default', true); ?>">Servizi</a></li>
	<li><a href="#">Contatti</a></li>*/ ?>
</ul>
<div class="login-top">
	<ul class="nav navbar-nav navbar-right">
		<!-- Link o pulsante per l'attivazione del dropdown -->
		<li><a href="<?= $this->url(array(
				'controller' => 'user',
				'action' => 'logout'
				),
				'default', true); ?>">Logout</a></li>
	</ul>
</div>