<ul class="nav navbar-right top-nav navbar-top-links">
	<li class="dropdown"><a href="#" class="dropdown-toggle"
		data-toggle="dropdown"><i class="fa fa-user"></i> Elia Pacioni <b
			class="caret"></b></a>
		<ul class="dropdown-menu">
			<li><a href="<?= $this->url(array(
					'controller' => 'admin',
					'action' => 'viewprofile'),
					'default', true); ?>"><i class="fa fa-fw fa-user"></i> Profilo</a></li>
			<li class="divider"></li>
			<li><a href="<?= $this->url(array(
					'controller' => 'admin',
					'action' => 'logout'),
					'default', true); ?>"><i class="fa fa-fw fa-power-off"></i> Log Out</a></li>
		</ul></li>
</ul>
<!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
<div class="collapse navbar-collapse navbar-ex1-collapse">
	<ul class="nav navbar-nav side-nav">
		<li><a href="<?= $this->url(array(
					'controller' => 'admin',
					'action' => 'index'),
					'default', true); ?>"><i class="fa fa-fw fa-dashboard"></i> Bacheca</a></li>
		<li><a href="javascript:;" data-toggle="collapse"
			data-target="#edifici"><i class="fa fa-fw fa-home"></i> Gestione
				Edifici <i class="fa fa-fw fa-caret-down"></i></a>
			<ul id="edifici" class="collapse">
				<li><a href="<?= $this->url(array(
					'controller' => 'admin',
					'action' => 'newbuilding'),
					'default', true); ?>">Inserisci Nuovo</a></li>
				<li><a href="<?= $this->url(array(
					'controller' => 'admin',
					'action' => 'viewbuilding'),
					'default', true); ?>">Modifica / Cancella</a></li>
			</ul></li>
		<li><a href="javascript:;" data-toggle="collapse" data-target="#staff"><i
				class="fa fa-fw fa-users"></i> Gestione Staff <i
				class="fa fa-fw fa-caret-down"></i></a>
			<ul id="staff" class="collapse">
				<li><a href="<?= $this->url(array(
					'controller' => 'admin',
					'action' => 'newstaff'),
					'default', true); ?>">Inserisci Nuovo</a></li>
				<li><a href=" <?= $this->url(array(
					'controller' => 'admin',
					'action' => 'viewstaff'),
					'default', true); ?>">Modifica / Cancella</a></li>
			</ul></li>
		<li><a href="javascript:;" data-toggle="collapse"
			data-target="#utenti"><i class="fa fa-fw fa-users"></i> Gestione
				Clienti <i class="fa fa-fw fa-caret-down"></i></a>
			<ul id="utenti" class="collapse">
				<li><a href="<?= $this->url(array(
					'controller' => 'admin',
					'action' => 'newuser'),
					'default', true); ?>">Inserisci Nuovo</a></li>
				<li><a href="<?= $this->url(array(
					'controller' => 'admin',
					'action' => 'viewuser'),
					'default', true); ?>">Modifica / Cancella</a></li>
			</ul></li>
		<li><a href="javascript:;" data-toggle="collapse"
			data-target="#faq"><i class="fa fa-fw fa-question"></i> Gestione
				Faq <i class="fa fa-fw fa-caret-down"></i></a>
			<ul id="faq" class="collapse">
				<li><a href="<?= $this->url(array(
					'controller' => 'admin',
					'action' => 'newfaq'),
					'default', true); ?>">Inserisci Nuovo</a></li>
				<li><a href="<?= $this->url(array(
					'controller' => 'admin',
					'action' => 'viewfaq'),
					'default', true); ?>">Modifica / Cancella</a></li>
			</ul></li>
	</ul>
</div>