<? $log = Zend_Auth::getInstance()->hasIdentity(); ?>

<ul class="nav navbar-nav">
	<li><a href="
	<?php if (!$log): ?>
	<?=$this->url ( array ('controller' => 'public','action' => 'index' ), 'default', true );?>
	<? else :?>
	<?=$this->url ( array ('controller' => 'user','action' => 'index' ), 'default', true );?>
	<? endif; ?>
	">Home</a></li>
	<li><a
		href="<?=$this->url ( array ('controller' => 'public','action' => 'viewstatic','staticPage' => 'chisiamo' ), 'default', true );?>">Chi Siamo</a></li>
	<li><a
		href="<?=$this->url ( array ('controller' => 'public','action' => 'viewstatic','staticPage' => 'servizi' ), 'default', true );?>">Servizi</a></li>
	<li><a
		href="<?=$this->url ( array ('controller' => 'public','action' => 'contact' ), 'default', true );?>">Contatti</a></li>
</ul>
<div class="login-top">
	<ul class="nav navbar-nav navbar-right">
	<?php if (!$log): ?>
		<li><a href="<?=$this->url ( array ('controller' => 'public','action' => 'login' ), 'default', true );?>">Login</a></li>
		<li><a href="<?=$this->url ( array ('controller' => 'public','action' => 'registration' ), 'default', true );?>">Registrati</a></li>
	<? else :?> 
		<li><a href="<?=$this->url ( array ('controller' => 'user','action' => 'logout' ), 'default', true );?>">Logout</a></li>
		<li><a href="<?=$this->url ( array ('controller' => 'user','action' => 'viewprofile' ), 'default', true );?>">Profilo</a></li>
	<?php endif; ?>
	</ul>
</div>