<?= $this->doctype(); ?>
<html>
<head>
<?= $this->headMeta(); ?>
<?= $this->headLink()->appendStylesheet($this->baseUrl('css/sb-admin.css'));?>
<?= $this->headTitle('SOPS Escape - Amministrazione'); ?>
<?= $this->headScript(); ?>
<meta name="viewport" content="width=device-width, initial-scale=1" />

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
	<div id="wrapper">
		<!-- Navigation -->
		<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target=".navbar-ex1-collapse">
					<span class="sr-only"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span> <span class="icon-bar"></span>
				</button>
				<?php if($this->authInfo('role') == 'admin') : ?>
				<a class="navbar-brand logo" href="<?= $this->url(array('controller' =>'admin', 'action' => 'index'), 'default', true); ?>">SOPS ESCAPE</a>
				<?php else :?>
				<a class="navbar-brand logo" href="<?= $this->url(array('controller' =>'staff', 'action' => 'index'), 'default', true); ?>">SOPS ESCAPE</a>
				<?php endif;?>
			</div>
			<!-- Top Menu Items -->
			<?= $this->render("_topnavadmin.phtml"); ?>
			
			<!-- /.navbar-collapse -->
		</nav>
		<div id="page-wrapper">
			<div class="container-fluid">
				<?= $this->layout()->content; ?>
			</div>
			<!-- /.container-fluid -->
		</div>
		<!-- /#page-wrapper -->
	</div>
	<!-- /#wrapper -->
</body>
</html>