<?= $this->doctype(); ?>
<html>
<head>
<?= $this->headMeta(); ?>
<?= $this->headLink()->appendStylesheet($this->baseUrl('css/stile.css'));?>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<?= $this->headTitle('SOPS Escape'); ?>
<?= $this->headScript(); ?>

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

</head>
<body>
	<!-- Fixed navbar -->
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse"
				data-target=".navbar-collapse">
				<span class="sr-only"></span> <span class="icon-bar"></span> <span
					class="icon-bar"></span> <span class="icon-bar"></span>
			</button>
			<?= $this->render('_topnavmain.phtml')?>
	
	
	</nav>
	<div class="img-principale hidden-xs">
	<?php	if($this->evacuare) : ?>
		<p class="text-center h1 allarme">
			<i class="fa fa-exclamation-triangle" ></i>
			Evacuare la zona, visualizza la <a href="<?= $this->url(array(
					'controller' => 'user',
					'action' => 'escape'),
					'default', true); ?>">mappa</a>
		</p>
	
	<?php else :?>
		<img src="<?= $this->baseUrl('css/images/blueprint.png'); ?>"
			class="img-responsive" alt="" title="" />
	<?php endif; ?>
	</div>
	<div class="container">
		<?php echo $this->layout()->content; ?>
	</div>
	<div class="container-fluid">
		<div class="row">
			<footer>
				<div class="col-sm-4">
					<p>&copy; SOPS S.p.A | Ancona | P.IVA 00000000000</p>
				</div>
				<div class="col-sm-4 text-center">
					<p>
						<a href="mailto:sops@sops.com"><i class="fa fa-envelope"></i>
							sops@sops.com</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a
							href="tel:+39 0000 000 000"><i class="fa fa-phone"></i> +39 0000
							000 000 </a>
					</p>
				</div>
				<div class="col-sm-4 text-right">
					<p>
						<a
							href="<?=$this->url ( array ('controller' => 'public','action' => 'faq' ), 'default', true );?>">F.A.Q.</a>
					</p>
				</div>
			</footer>
		</div>
	</div>
	<div id="back_to_top">
		<a href="#"><i class="fa fa-caret-square-o-up fa-4x"></i></a>
	</div>
</body>
</html>