<div class="row">
	<div class="col-sm-12">
		<hgroup class="text-center" id="titolo">
			<h1>Via di fuga</h1>
			<h4>Nell'immagine viene mostrata la via di fuga riferita alla
				posizione registrata</h4>
		</hgroup>
		<hr />
	</div>
	<div class="col-sm-12">
	<?php if(!$this->escape_map == NULL) :?>
		<img style="display: block; margin: 0 auto;" src=" <?= $this->baseUrl("/images/escape/$this->escape_map");?>" alt="Via di Fuga" class="img-responsive" />
	<?php else :?>
		<h2 class="text-center">Non hai definito una posizione</h2>
	<?php endif;?>
	</div>
</div>