<div class="row icone-principali">
	<div class="col-sm-4">
		<div class="text-center">
				<?php if($this->position == NULL) : ?>
			<a href="<?= $this->url(array(
					'controller' => 'user',
					'action' => 'registerposition'),
					'default', true); ?>"> <i class="fa fa-map-marker fa-5x"></i><br /> 
			<span class="h3">Registra La Tua Posizione</span></a>
			<p>Testo di prova testo di prova</p>
		<?php else :?>
			<a href="<?= $this->url(array(
					'controller' => 'user',
					'action' => 'deleteposition'),
					'default', true); ?>"> <i class="fa fa-map-marker fa-5x"></i><br /> 
			<span class="h3">Cancella la tua posizione</span></a>
			<p>Testo di prova testo di prova</p>
		<?php endif; ?>
		</div>
	</div>
	<div class="col-sm-4">
		<div class="text-center">
			<a href="<?= $this->url(array(
					'controller' => 'user',
					'action' => 'alert'),
					'default', true); ?>"> <i class="fa fa-exclamation-triangle fa-5x"></i><br /> <span
				class="h3">Segnala Pericolo</span></a>
			<p>Testo di prova testo di prova</p>
		</div>
	</div>
	<div class="col-sm-4">
		<div class="text-center">
			<a href="<?= $this->url(array(
					'controller' => 'user',
					'action' => 'escape'),
					'default', true); ?>"> <i class="fa fa-info fa-5x"></i><br /> <span class="h3">Uscita
					D'Emergenza</span></a>
			<p>Testo di prova testo di prova</p>
		</div>
	</div>
</div>
<hr />
<div class="row">
	<div class="col-sm-12">
		<h2 class="text-center">I primi passi</h2>
		<br />
	</div>
	<div class="col-sm-3">
		<img src="<?= $this->baseUrl('css/images/manuale.png')?>" class="img-responsive" alt="" title="" />
	</div>
	<div class="col-sm-9">
		<article class="text-justify">
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec
				consectetur pellentesque libero a auctor. Mauris mollis elit quis
				enim gravida sodales. Morbi sodales ultrices mollis. In libero nisl,
				gravida in gravida dignissim, mattis a neque. Aenean diam sem, porta
				non vestibulum in, mollis a eros. Nam vestibulum tempus urna, sit
				amet dignissim ipsum pellentesque eget. Nullam ultrices felis non
				purus iaculis, non gravida ex faucibus.</p>

			<p>Pellentesque malesuada massa quam. Cras luctus accumsan sapien id
				euismod. Pellentesque tincidunt, dui a interdum tempus, nunc ex
				molestie eros, vitae ultricies justo erat in mi. Nulla dignissim
				diam eu eros ornare rutrum a id metus. Ut ultrices, dui in commodo
				accumsan, urna purus venenatis libero, vel placerat leo ligula
				porttitor est. Sed nec hendrerit odio. Quisque pretium, orci a
				porttitor dapibus, ex nisi commodo eros, eget vehicula nisl sapien
				vel lectus. Sed nec tortor vestibulum, tincidunt enim rhoncus,
				tristique velit.</p>

			<p>Morbi in risus sed odio fringilla semper nec at lacus. In hac
				habitasse platea dictumst. Vivamus lobortis dui metus. Aliquam vel
				magna id augue malesuada congue. Vivamus neque nunc, bibendum quis
				erat quis, laoreet condimentum dui. Quisque vehicula erat ut
				pulvinar lacinia. Donec non odio sed leo aliquet maximus in id
				tellus. Nam congue nisl nec mi laoreet sollicitudin. Donec in
				venenatis ante. Maecenas pellentesque massa id purus tempor, non
				fermentum lacus volutpat. Interdum et malesuada fames ac ante ipsum
				primis in faucibus. Sed ac sodales turpis. Cras quis urna in sem
				consequat bibendum. Aliquam fermentum mi eu sagittis ultrices.
				Nullam non sem eu nulla auctor elementum. Vestibulum pharetra
				porttitor purus, at euismod nisi egestas ut. Duis ullamcorper nisi
				sit amet nulla tempor vulputate. Sed lacinia augue est, egestas
				egestas elit pretium vel.</p>
		</article>
	</div>
</div>