<script>
	$(function(){
		$('#building_code').change(function(event){
			$.ajax({
					type: 'POST',
					url: '<?= $this->url(array('controller' => 'user', 'action' => 'register'), 'default'); ?>',
					data: "code="+$('#building_code').val(),
					datatype: 'json',
					success: setFloor
			});
		});			
	});


	function setFloor(data){
		$('#floor_number').find('option').remove();
		
        var floor = parseInt(data['floor_number']);
        
		for(var i=0; i<floor; i++){
			$('#floor_number').append("<option>" + i + "</option>");
		};
		
	}
</script>

<div class="row">
	<div class="col-sm-12">
		<h1 class="text-center" id="titolo">Registra La Tua Posizione</h1>
		<hr />
	</div>
	<div class="col-sm-4">
		<?=$this->registerpositionForm; ?>
	</div>
	<div class="col-sm-8">
		<!-- <img src="images/planimetria.jpg" class="img-responsive" /> -->
	</div>
</div>