<!-- Page Heading -->
<div class="row">
	<div class="col-lg-12">
		<ol class="breadcrumb">
			<li class="active"><i class="fa fa-dashboard"></i> Bacheca</li>
		</ol>
	</div>
	<div class="col-sm-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">
					<i class="fa fa-money fa-fw"></i> Gestione Segnalazioni
				</h3>
			</div>
			<div class="panel-body">
				<div class="table-responsive">
					<table class="table table-bordered table-hover table-striped">
						<thead>
							<tr>
								<th><i class="fa fa-trash-o"></i></th>
								<th><i class="fa fa-file-o"></i></th>
								<th>Edificio</th>
								<th>Luogo</th>
								<th>Tipologia</th>
								<th>Utente</th>
								<th>Data & Ora</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td><i class="fa fa-times"></i></td>
								<td><i class="fa fa-pencil-square-o"></i></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
							</tr>
						</tbody>
					</table>
				</div>
				<!--paginator-->
				<div class="text-center">
				</div>
			</div>
		</div>
		<!-- /.container-fluid -->
	</div>
</div>
<!-- /.row -->