<!-- Page Heading -->
<div class="row">
	<div class="col-lg-12">
		<ol class="breadcrumb">
			<li class="active"><i class="fa fa-dashboard"></i> Bacheca</li>
		</ol>
	</div>
	<div class="col-sm-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">
					<i class="fa fa-money fa-fw"></i> Gestione Segnalazioni
				</h3>
			</div>
			<div class="panel-body">
				<div class="table-responsive">
					<table class="table table-bordered table-hover table-striped">
						<thead>
							<tr>
								<th>Edificio</th>
								<th>Piano</th>
								<th>Zona</th>
								<th>Tipologia</th>
								<th>Utente</th>
								<th>Data & Ora</th>
								<th>Progresso</th>
							</tr>
						</thead>
						<tbody>
						<?php foreach ($this->alert as $alert) : ?>
							<tr>
								<td><?= $alert->building;?></td>
								<td><?= $alert->floor;?></td>
								<td><?= $alert->zone; ?></td>
								<td><?= $alert->type?></td>
								<td><?= $alert->user_code?></td>
								<td><?= $alert->date_time?></td>
								<td><?= $alert->progress?></td>
							</tr>
						<?php endforeach; ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<!-- /.container-fluid -->
	</div>
</div>
<!-- /.row -->