<?php $this->headScript()->captureStart()?>
	$(function(){
		$('#building_code').change(function(event){
			$.ajax({
					type: 'POST',
					url: '<?= $this->url(array('controller' => 'user', 'action' => 'floornumber'), 'default'); ?>',
					data: "code="+$('#building_code').val(),
					datatype: 'json',
					success: setFloor
			});
		});			
	});


	function setFloor(data){
		$('#number').find('option').remove();
		$('#zone_number').find('option').remove();
		$('#number').append('<option>-- Select --</option>'); 
		var floor = parseInt(data['floor_number']); 
		$.each(data,
		function(key, val){ 
			$('#number').append('<option value="' + val['code'] + '">' + val['number'] + '</option>');
        });
	}
<?php $this->headScript()->captureEnd()?>

<div class="row">
	<div class="col-sm-12">
		<hgroup id="titolo">
			<h2 class="text-center">Modifica Piano</h2>
			<h4 class="text-center">Utilizza questa form modificare un piano</h4>
		</hgroup>
		
		<?= $this->modifyfloorForm; ?>
		
	</div>
</div>