<?php $this->headScript()->captureStart()?>
	$(function(){
		$('#building_code').change(function(event){
			$.ajax({
					type: 'POST',
					url: '<?= $this->url(array('controller' => 'admin', 'action' => 'floornumber'), 'default'); ?>',
					data: "code="+$('#building_code').val(),
					datatype: 'json',
					success: setFloor
			});
		});			
	});


	function setFloor(data){
		$('#number').find('option').remove();
		$('#zone_code').find('option').remove();
		$('#number').append('<option>-- Select --</option>'); 
		var floor = parseInt(data['floor_number']); 
		$.each(data,
		function(key, val){ 
			$('#number').append('<option value="' + val['code'] + '">' + val['number'] + '</option>');
        });
		
	}
	$(function(){
		$('#number').change(function(event){
			$.ajax({
				type: 'POST',
				url: '<?= $this->url(array('controller' => 'admin', 'action' => 'zonenumber'), 'default'); ?>',
				data: "code="+$('#number').val(),
				datatype: 'json',
				success: setZone
			});
		});
	});
	
	function setZone(data){
		$('#zone_code').find('option').remove();
		$('#zone_code').append('<option>-- Select --</option>'); 
		delete data['floor_map']; var zone = parseInt(data['zone_number']);
		$.each(data, function(key, val){ 
			$('#zone_code').append('<option value="' + val['code'] + '">' + val['number'] + '</option>');
	    });
	}
	
	function setEscape_map(data){
		$('#zone_code').find('option').remove();
		
        var zone = parseInt(data['number']);
        
		for(var i=0; i<number; i++){
			$('#zone_code').append("<option>" + i + "</option>");
		};
		
	}
<?php $this->headScript()->captureEnd()?>


<div class="row">
	<div class="col-sm-12">
		<hgroup id="titolo">
			<h2 class="text-center">Nuova Via di Fuga</h2>
			<h4 class="text-center">Utilizza questa form per inserire una nuova via di fuga per una Zona</h4>
		</hgroup>
		<?= $this->escapeForm; ?>
	</div>
</div>