<script>
	$(function(){
		$('#building_code').change(function(event){
			$.ajax({
					type: 'POST',
					url: '<?= $this->url(array('controller' => 'admin', 'action' => 'completefloor'), 'default'); ?>',
					data: "code="+$('#building_code').val(),
					datatype: 'json',
					success: setFloor
			});
		});			
	});


	function setFloor(data){
		$('#number').find('option').remove();
		
        var floor = parseInt(data['floor_number']);
        
		for(var i=0; i<floor; i++){
			$('#number').append("<option>" + i + "</option>");
		};
		
	}
</script>


<div class="row">
	<div class="col-sm-12">
		<hgroup id="titolo">
			<h2 class="text-center">Nuovo Piano</h2>
			<h4 class="text-center">Utilizza questa form per inserire una nuova
				planimetria per un Piano</h4>
		</hgroup>
		<?= $this->floorForm; ?>
	</div>
</div>