<?php $this->headScript()->captureStart()?>
	$(function(){
		$('#building_code').change(function(event){
			$('#alert_error').remove();
			$.ajax({
					type: 'POST',
					url: '<?= $this->url(array('controller' => 'admin', 'action' => 'completefloor'), 'default'); ?>',
					data: "code="+$('#building_code').val(),
					datatype: 'json',
					success: setFloor
			});
		});			
	});


	function setFloor(data){
		$('#number').find('option').remove();
		
        var floor = parseInt(data['floor_number']);
        $('#number').append("<option>--Select--</option>");
		for(var i=0; i<floor; i++){
			$('#number').append('<option>' + i + '</option>');
		};
		
	}

	$(function(){
		$('#number').change(function(event){
			$('#alert_error').remove();
			$('#add').prop("disabled",false);	
			$.ajax({
				type: 'POST',
				url: '<?= $this->url(array('controller' => 'admin', 'action' => 'validatefloor'), 'default');?>',
				data: "floor="+$('#number').val() + "&building="+$('#building_code').val(),
				datatype: 'json',
				success: validateFloor
			});
		});			
	});

	function validateFloor(data){
		if(data == true){
			$('#titolo').append('<p id="alert_error" class="alert h1">Piano già esistente, usare il form di modifica o crearne uno nuovo</p>');
			$('#add').prop("disabled",true);
		}
	}
<?php $this->headScript()->captureEnd()?>


<div class="row">
	<div class="col-sm-12">
		<hgroup id="titolo">
			<h2 class="text-center">Nuovo Piano</h2>
			<h4 class="text-center">Utilizza questa form per inserire una nuova
				planimetria per un Piano</h4>
		</hgroup>
		<?= $this->floorForm; ?>
	</div>
</div>