<div class="row">
	<div class="col-sm-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">
					<i class="fa fa-money fa-fw"></i> Gestione Edifici
				</h3>
			</div>
			<div class="panel-body">
				<div class="table-responsive">
					<table class="table table-bordered table-hover table-striped">
						<thead>
							<tr>
								<th><i class="fa fa-trash-o"></i></th>
								<th><i class="fa fa-file-o"></i></th>
								<th>Domanda</th>
								<th>Risposta</th>
							</tr>
						</thead>
						<tbody>
						<?php foreach ($this->faq as $faq) : ?>
							<tr>
								<td><a href="<?=$this->url(array(
													'controller' => 'admin',
													'action' => 'deletefaq',
													'code' => $faq->code
													), 
													'default', true); ?>"><i class="fa fa-times"></i></a></td>
								<td><a href="<?=$this->url(array(
													'controller' => 'admin',
													'action' => 'modifyfaq',
													'code' => $faq->code
													), 
													'default', true); ?>"><i class="fa fa-pencil-square-o"></i></a></td>
								<td><?= $faq->question;?></td>
								<td><?= $faq->answer;?></td>
							</tr>
						<?php endforeach; ?>
						</tbody>
					</table>
				</div>
				<!--paginator-->
				<div class="text-center">
				</div>
			</div>
		</div>
		
	</div>
</div>