<div class="row">
	<div class="col-sm-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">
					<i class="fa fa-money fa-fw"></i> Gestione Edifici
				</h3>
			</div>
			<div class="panel-body">
				<div class="table-responsive">
					<table class="table table-bordered table-hover table-striped">
						<thead>
							<tr>
								<th><i class="fa fa-trash-o"></i></th>
								<th><i class="fa fa-file-o"></i></th>
								<th>Edificio</th>
								<th>Address</th>
								<th>Floor Number</th>
								<th>Description</th>
							</tr>
						</thead>
						<tbody>
						<?php foreach ($this->building as $building) : ?>
							<tr>
								<td><a href="<?=$this->url(array(
													'controller' => 'admin',
													'action' => 'deletebuilding',
													'code' => $building->code
													), 
													'default', true); ?>"><i class="fa fa-times"></i></a></td>
								<td><a href="<?=$this->url(array(
													'controller' => 'admin',
													'action' => 'modifybuilding',
													'code' => $building->code
													), 
													'default', true); ?>"><i class="fa fa-pencil-square-o"></i></a></td>
								<td><?= $building->name;?></td>
								<td><?= $building->address;?></td>
								<td><?= $building->floor_number;?></td>
								<td><?= $building->desc_short;?></td>
							</tr>
						<?php endforeach; ?>
						</tbody>
					</table>
				</div>
				<!--paginator-->
				<div class="text-center">
				</div>
			</div>
		</div>
		
	</div>
</div>