<div class="row">
	<div class="col-sm-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">
					<i class="fa fa-money fa-fw"></i> Gestione Staff
				</h3>
			</div>
			<div class="panel-body">
				<div class="table-responsive">
					<table class="table table-bordered table-hover table-striped">
						<thead>
							<tr>
								<th><i class="fa fa-trash-o"></i></th>
								<th><i class="fa fa-file-o"></i></th>
								<th>Username</th>
								<th>Nome</th>
								<th>Cognome</th>
								<th>Email</th>
							</tr>
						</thead>
						<tbody>
						<?php foreach ($this->staff as $staff) : ?>
							<tr>
								<td><a href="<?=$this->url(array(
													'controller' => 'admin',
													'action' => 'deletestaff',
													'user' => $staff->user
													), 
													'default', true); ?>"><i class="fa fa-times"></i></a></td>
								<td><a href="<?=$this->url(array(
													'controller' => 'admin',
													'action' => 'modifystaff',
													'user' => $staff->user
													), 
													'default', true); ?>"><i class="fa fa-pencil-square-o"></i></a></td>
								<td><?= $staff->user;?></td>
								<td><?= $staff->name;?></td>
								<td><?= $staff->surname;?></td>
								<td><?= $staff->mail;?></td>
							</tr>
						<?php endforeach; ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		
	</div>
</div>