<div class="row">
	<div class="col-lg-12">
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<img src="" class="img-user img-circle img-thumbnail img-responsive">
				</div>
				<div class="col-sm-3 utente">
					<h3>Elia</h3>
					<h5>eliapacioni@gmail.com</h5>
				</div>
				<div class="col-sm-3 dati-utente">
					<h5>Lingua</h5>
					<h5>Italiano</h5>
				</div>
				<div class="col-sm-3 password">
					<a href="#" class="h4"><small>Reimposta Password</small></a>
				</div>
			</div>
		</div>
	</div>
</div>