<div class="row">
	<div class="col-lg-12">
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<img src="<?= $this->baseUrl("css/images/user.jpg");?>" class="img-user img-circle img-thumbnail img-responsive">
				</div>
				<div class="col-sm-3 utente">
					<p class="h3"><?= $this->authInfo('name');?> <?= $this->authInfo('surname');?></p>
					<p class="h5">Username : <?= $this->authInfo('user');?></p>
				</div>
				<div class="col-sm-3 dati-utente">
					<h3>Ruolo</h3>
					<h5><?= strtoupper($this->authInfo('role'));?></h5>
				</div>
				<div class="col-sm-3 password">
					<a href="#" class="h4"><small>Modifica profilo</small></a>
				</div>
			</div>
		</div>
	</div>
</div>